name: ci

on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm
      - run: npm ci
      - run: npm run build
      # If you added a separate typecheck, include it:
      # - run: npm run typecheck
